Raft Vault Backend
kubevault/operator pull request #349
Opened 2021-05-18 12:43 UTC by sakiib

Signed-off-by: sakibalamin <sakibalamin@appscode.com>

2021-06-09 14:55 UTC, tks98 commented
Is there any update on if/when this will be merged? Being able to use this operator with Vault utilizing integrated raft storage would be hugely beneficial to my team. Thank you!

2021-06-25 12:09 UTC, kamolhasan requested changes

2021-06-25 12:09 UTC, kamolhasan commented on pkg/vault/storage/raft/raft.go
> +				Name:      "data",
const VautlVolumeMountData = "data"

2021-06-25 12:09 UTC, kamolhasan commented on pkg/vault/storage/raft/raft.go
> +					Name:      raftTLSAssetVolume,
const VautlServerVolumeMountStorageCert = "storage-cert"

2021-06-25 12:09 UTC, kamolhasan commented on pkg/vault/storage/raft/raft.go
> +	if o.NodeID != "" {
We don't this one. Taken from env.

2021-06-25 12:09 UTC, kamolhasan commented on pkg/vault/storage/raft/raft.go
> +		// e.g: retryJoin = append(retryJoin, fmt.Sprint(` leader_api_addr = "https://vault-0.vault-internal.demo.svc:8200"`))
Use more relevant comment

2021-06-25 12:09 UTC, kamolhasan commented on pkg/vault/storage/raft/raft.go
> +			retryJoin = append(retryJoin, fmt.Sprintf(` leader_ca_cert_file = "%s"`, filepath.Join(RaftTLSAssetDir, RaftClientCaName)))
Use vs.CertificateMountPath() helper method

2021-06-25 12:09 UTC, kamolhasan commented on pkg/vault/unsealer/aws/aws_kms_ssm.go
> +	Backend string
remove unused params

2021-06-25 12:09 UTC, kamolhasan commented on pkg/vault/util/vault_config.go
> +		params = append(params, fmt.Sprintf(`tls_cert_file = "%s"`, filepath.Join(VaultTLSAssetDir, core.TLSCertKey)))
Use vs.CertificateMountPath() helper method

2021-06-28 05:25 UTC, kamolhasan requested changes

2021-06-28 05:25 UTC, kamolhasan commented on pkg/vault/storage/raft/raft.go
> +	RaftCertificatePath = "/etc/vault/tls/"
Remove this one

2021-06-28 05:25 UTC, kamolhasan commented on pkg/vault/storage/raft/raft.go
> +				Name:      "data",
VautlVolumeMountConfig = "config"

2021-06-28 13:51 UTC, kamolhasan submitted a review, later dismissed
LGTM!

2021-06-28 13:52 UTC, kamolhasan approved these changes

2021-06-28 14:26 UTC, merged